version: '3.5'

services:
  dynamodb:
    image: amazon/dynamodb-local
    networks:
      - serverless
    ports:
      - '8000:8000'
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'

networks:
  serverless:
    name: serverless

volumes:
  dynamodata: {}